# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1034a1c2e331635991c2b70e132c53094033e37d24025403729cb32a402cdf28cbcaa365d8531106ba7c9e832ec833c1763c54ffda0a42cbe9f51277202bcaf4

test:
  secret_key_base: 07374b78481e21ced96bbcc7375019398a49f3b214d640aeb07e77339671f48401ec06d0a3cd682962e975cfdda8ec4a7417b2a0a99b2944e583792af418486c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
